// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyRszp9YjvF5iPmK_V5fAt-wsjNhV2S0k',
    appId: '1:958032766959:web:476f83e7f04cc1114db81a',
    messagingSenderId: '958032766959',
    projectId: 'ecollege-dd3a3',
    authDomain: 'ecollege-dd3a3.firebaseapp.com',
    storageBucket: 'ecollege-dd3a3.appspot.com',
    measurementId: 'G-YCJVZ866HW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUiu22FqaiPwRfZ0J5obtz0md2Er93D0g',
    appId: '1:958032766959:android:2040b0a3905a4dce4db81a',
    messagingSenderId: '958032766959',
    projectId: 'ecollege-dd3a3',
    storageBucket: 'ecollege-dd3a3.appspot.com',
  );
}
